# Required packages
install.packages("BiocManager")
install.packages('digest', repos = c('https://eddelbuettel.r-universe.dev', 'https://cloud.r-project.org'))
install.packages("devtools")
install.packages("doParallel")
install.packages("doRNG")
install.packages("doSNOW")
install.packages("dplyr")
install.packages("foreach")
install.packages("igraph")
install.packages("Kendall")
install.packages("modEvA")
install.packages("patchwork")
install.packages("progress")
install.packages("snow")
install.packages("ggplot2")
install.packages("RcppArmadillo")
BiocManager::install("ComplexHeatmap")
BiocManager::install("edgeR")
devtools::install_github("statOmics/tradeSeq")
