# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SRM_model_fit_sparse <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_inferCSN_SRM_model_fit_sparse', PACKAGE = 'inferCSN', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

SRM_model_fit_dense <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_inferCSN_SRM_model_fit_dense', PACKAGE = 'inferCSN', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

SRM_model_fit_CV_sparse <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_inferCSN_SRM_model_fit_CV_sparse', PACKAGE = 'inferCSN', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

SRM_model_fit_CV_dense <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_inferCSN_SRM_model_fit_CV_dense', PACKAGE = 'inferCSN', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

R_matrix_column_get_dense <- function(mat, col) {
    .Call('_inferCSN_R_matrix_column_get_dense', PACKAGE = 'inferCSN', mat, col)
}

R_matrix_column_get_sparse <- function(mat, col) {
    .Call('_inferCSN_R_matrix_column_get_sparse', PACKAGE = 'inferCSN', mat, col)
}

R_matrix_rows_get_dense <- function(mat, rows) {
    .Call('_inferCSN_R_matrix_rows_get_dense', PACKAGE = 'inferCSN', mat, rows)
}

R_matrix_rows_get_sparse <- function(mat, rows) {
    .Call('_inferCSN_R_matrix_rows_get_sparse', PACKAGE = 'inferCSN', mat, rows)
}

R_matrix_vector_schur_product_dense <- function(mat, u) {
    .Call('_inferCSN_R_matrix_vector_schur_product_dense', PACKAGE = 'inferCSN', mat, u)
}

R_matrix_vector_schur_product_sparse <- function(mat, u) {
    .Call('_inferCSN_R_matrix_vector_schur_product_sparse', PACKAGE = 'inferCSN', mat, u)
}

R_matrix_vector_divide_dense <- function(mat, u) {
    .Call('_inferCSN_R_matrix_vector_divide_dense', PACKAGE = 'inferCSN', mat, u)
}

R_matrix_vector_divide_sparse <- function(mat, u) {
    .Call('_inferCSN_R_matrix_vector_divide_sparse', PACKAGE = 'inferCSN', mat, u)
}

R_matrix_column_sums_dense <- function(mat) {
    .Call('_inferCSN_R_matrix_column_sums_dense', PACKAGE = 'inferCSN', mat)
}

R_matrix_column_sums_sparse <- function(mat) {
    .Call('_inferCSN_R_matrix_column_sums_sparse', PACKAGE = 'inferCSN', mat)
}

R_matrix_column_dot_dense <- function(mat, col, u) {
    .Call('_inferCSN_R_matrix_column_dot_dense', PACKAGE = 'inferCSN', mat, col, u)
}

R_matrix_column_dot_sparse <- function(mat, col, u) {
    .Call('_inferCSN_R_matrix_column_dot_sparse', PACKAGE = 'inferCSN', mat, col, u)
}

R_matrix_column_mult_dense <- function(mat, col, u) {
    .Call('_inferCSN_R_matrix_column_mult_dense', PACKAGE = 'inferCSN', mat, col, u)
}

R_matrix_column_mult_sparse <- function(mat, col, u) {
    .Call('_inferCSN_R_matrix_column_mult_sparse', PACKAGE = 'inferCSN', mat, col, u)
}

R_matrix_normalize_dense <- function(mat_norm) {
    .Call('_inferCSN_R_matrix_normalize_dense', PACKAGE = 'inferCSN', mat_norm)
}

R_matrix_normalize_sparse <- function(mat_norm) {
    .Call('_inferCSN_R_matrix_normalize_sparse', PACKAGE = 'inferCSN', mat_norm)
}

R_matrix_center_dense <- function(mat, X_normalized, intercept) {
    .Call('_inferCSN_R_matrix_center_dense', PACKAGE = 'inferCSN', mat, X_normalized, intercept)
}

R_matrix_center_sparse <- function(mat, X_normalized, intercept) {
    .Call('_inferCSN_R_matrix_center_sparse', PACKAGE = 'inferCSN', mat, X_normalized, intercept)
}

asMatrix <- function(rp, cp, z, nrows, ncols) {
    .Call('_inferCSN_asMatrix', PACKAGE = 'inferCSN', rp, cp, z, nrows, ncols)
}

asMatrixParallel <- function(rp, cp, z, nrows, ncols) {
    .Call('_inferCSN_asMatrixParallel', PACKAGE = 'inferCSN', rp, cp, z, nrows, ncols)
}

tableToMatrix <- function(weight_table) {
    .Call('_inferCSN_tableToMatrix', PACKAGE = 'inferCSN', weight_table)
}

